# -*- coding: utf-8 -*-
"""Requirement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TQMd20R-mEyX0bdjJCzCgQzt7cmSXIMC
"""

pip install bokeh

!pip install streamlit
import streamlit as st

from bokeh.plotting import figure, show
# Our main plotting package (must have explicit import of submodules)
import bokeh.io
import bokeh.plotting

# Enable viewing Bokeh plots in the notebook
bokeh.io.output_notebook()